algorithm: iomatch
save_dir: ./saved_models/openset_cv
save_name: iomatch_cifar100_80_1
resume: True
load_path: ./saved_models/openset_cv/iomatch_cifar100_80_1/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 256
num_train_iter: 262144
num_eval_iter: 1024
num_labels: 80
batch_size: 64
eval_batch_size: 256
p_cutoff: 0.95
q_cutoff: 0.5
mb_loss_ratio: 1.0
ulb_loss_ratio: 1.0
op_loss_ratio: 1.0
use_rot: False
uratio: 7
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.001
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: wrn_28_2
net_from_name: False
data_dir: ./data
dataset: cifar100_openset
train_sampler: RandomSampler
num_classes: 20
num_workers: 1
seed: 1
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10055
dist_backend: nccl
gpu: None
